// <auto-generated />
using System;
using ASPNetCoreWebAPI.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPNetCoreWebAPI.Migrations {
    [DbContext (typeof (DataContext))]
    [Migration ("20191230073759_ASPNetCoreWebAPI.DataContext")]
    partial class ASPNetCoreWebAPIDataContext {
        protected override void BuildTargetModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation ("Relational:MaxIdentifierLength", 128)
                .HasAnnotation ("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity ("ASPNetCoreWebAPI.Entities.User", b => {
                b.Property<int> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasAnnotation ("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string> ("FirstName");

                b.Property<string> ("LastName");

                b.Property<byte[]> ("PasswordHash");

                b.Property<byte[]> ("PasswordSalt");

                b.Property<string> ("Username");

                b.HasKey ("Id");

                b.ToTable ("Users");
            });
#pragma warning restore 612, 618
        }
    }
}